spring:
  data:
    mongodb:
      username: chirayu
      password: chirayu
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  observations:
    http:
      server:
        requests:
          ignore-patterns: "/actuator/**,/actuator"